name: my_tasks
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.2

  timeline_tile: ^2.0.0
  intl: ^0.18.0

  animations: ^2.0.7

  top_snackbar_flutter: ^3.1.0
  
  flutter_lints: ^2.0.2
  get:

  shared_preferences: ^2.2.1

  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  fonts:
  - family: IBMPlexSansArabic
    fonts:
      - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
      - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
      - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
      - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
      - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
      - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
      - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf

      - asset: assets/fonts/ArefRuqaa-Bold.ttf
      - asset: assets/fonts/ArefRuqaa-Regular.ttf

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/introduction_animation/
